# Generated by Django 5.0.3 on 2024-03-27 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_naim_product_name'),
        ('warehouses', '0002_alter_stock_options_alter_stock_occupancy_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('purchase_price', models.FloatField(verbose_name='Стоймасть закупки')),
                ('sales_price', models.FloatField(blank=True, verbose_name='Стоймасть сбыта')),
                ('purchase_date', models.DateField(verbose_name='Дата поступления')),
                ('sales_date', models.DateField(blank=True, verbose_name='Дата сбыта')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.stock')),
            ],
        ),
    ]
