# Generated by Django 5.0.3 on 2024-03-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sales_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата сбыта'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sales_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Стоймасть сбыта'),
        ),
    ]
