# Generated by Django 5.0.3 on 2024-03-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_item_sales_date_alter_item_sales_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sold',
            field=models.BooleanField(default=False, verbose_name='Сбыто'),
        ),
    ]
