# Generated by Django 5.0.3 on 2024-03-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_item_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='soldQuantity',
            field=models.IntegerField(default=0, verbose_name='Количество cбыто'),
        ),
    ]
