# Generated by Django 5.0.3 on 2024-03-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_item_soldquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='available',
            field=models.BooleanField(default=True, verbose_name='доступно'),
        ),
    ]
