# Generated by Django 5.0.3 on 2024-05-09 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_item_responsible'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
