# Generated by Django 5.0.3 on 2024-05-09 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='site_link',
        ),
    ]
