# Generated by Django 5.0.3 on 2024-03-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('number_racks', models.IntegerField(verbose_name='Количество стиложей')),
                ('occupancy_status', models.FloatField(verbose_name='Заполниность стиложей')),
            ],
        ),
    ]
